### ISSUE TITLE
csv writer

### ISSUE THREAD

**Issue by ArtemKonshyn** [finchf/oop#1]
https://github.com/finchf/oop/blob/9a75f6c98491528069d5cbb17dc7d67a3a1619a2/HomeWork1_PhoneAndChess.py#L19

Не треба зваливати все в одну купу
тут краще логування винести в окрему функцію, або навіть клас

і логувати треба було номер телефону теж)

**Comment by finchf** [comment]
виніс в новий class CallLogger 
логування телефону теж додано
https://github.com/finchf/oop/blob/3e22f8b9e889dae516053cc1d46e3fb170e3f4db/HomeWork2_Praktika1_andEmployee.py#L94
