### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by ArtemKonshyn** [finchf/oop#2]
https://github.com/finchf/oop/blob/9a75f6c98491528069d5cbb17dc7d67a3a1619a2/HomeWork1_PhoneAndChess.py#L51

краще зробити константи

**Comment by finchf** [comment]
вніс виправлення 
https://github.com/finchf/oop/blob/3e22f8b9e889dae516053cc1d46e3fb170e3f4db/HomeWork2_Praktika1_andEmployee.py#L123
