### ISSUE TITLE
set color

### ISSUE THREAD

**Issue by ArtemKonshyn** [finchf/oop#3]
https://github.com/finchf/oop/blob/9a75f6c98491528069d5cbb17dc7d67a3a1619a2/HomeWork1_PhoneAndChess.py#L58

у таску написано змінити колір
set - це більше про ф-цію, яка щось приймає і потім змінює

і, якщо чесно, логіка дуже важка як для двох констант

**Comment by finchf** [comment]
вніс виправлення 
https://github.com/finchf/oop/blob/3e22f8b9e889dae516053cc1d46e3fb170e3f4db/HomeWork2_Praktika1_andEmployee.py#L139
